[package]
name = "logbook-integrity"
version = "0.1.0"
description = "A command-line tool for parsing and validating journal entries"
edition = "2021"

[dependencies]
time = { version = "0.3.36", features = [ "macros", "parsing" ] }
